### ISSUE TITLE
云数据库 Cloud DB 几个问题

### ISSUE THREAD

**Issue by gybin02** [AppGalleryConnect/agc-android-demos#1]
看完Cloud DB文档： 
https://developer.huawei.com/consumer/cn/doc/development/AppGallery-connect-Guides/agc-clouddb-get-started-0000001127676473

有几个问题，帮忙答复下， 不然感觉无法咋真实的环境下使用

1.  表如何 创建 id自增 主键？ 
2. 关联表查询 如何实现。都要分为多次查询吗？ 比如 你的例子中， 图书表book  和 用户表user  怎么查出 user_id =1 的用户的所有图书内容，同时包含 用户name 等
3. 日期字段怎么定义

**Comment by yycccc91** [comment]
1. 目前我们还不支持id自增的主键
2. 可以使用组合查询的方式来实现，具体可以参考此文档：https://developer.huawei.com/consumer/cn/doc/development/AppGallery-connect-Guides/agc-clouddb-query-data-0000001080976888#section487052675515
3. 日期字段就是Date类型

**Comment by gybin02** [comment]
> 1. 目前我们还不支持id自增的主键
> 2. 可以使用组合查询的方式来实现，具体可以参考此文档：https://developer.huawei.com/consumer/cn/doc/development/AppGallery-connect-Guides/agc-clouddb-query-data-0000001080976888#section487052675515
> 3. 日期字段就是Date类
关于第二点：
  现在文档都是 单表的聚合查询，能提供一些跨表查询的文档吗？ 或者实现一个简单的TODO功能，包含user表 和 TODO 表

**Comment by yycccc91** [comment]
不好意思，暂时还没有支持跨表查询的计划
